admin:
  ip: 0.0.0.0
  port: 9990

routers:
- protocol: http
  servers:
  - ip: 0.0.0.0
    port: 1080
  dtab: |
    /svc/foo => /mock/bin/f6832ece-fe44-4a1d-acd4-cb28d406fd67;
    /mock => /$/inet/mockbin/8080;